### ISSUE TITLE
Request for participation

### ISSUE THREAD

**Issue by tvararu** [DiscoverMeteor/DiscoverMeteor_Ro#3]
Hello / Salut!

I'm interested in helping out with the Romanian translation for the book. I'm currently working on racking up a higher contribution streak on Github, so I'm sure I'll find a few spare days to hammer in a few commits.

**Comment by virgotopia** [comment]
Hello Theodor,
You are welcome! Thanks for your comments.
I added you to the DiscoverMeteor_Ro repo and I supposed Sasha will add you to the _En version so you can start.

**Comment by tvararu** [comment]
Thanks! :+1:

**Comment by virgotopia** [comment]
My fault, you already have all access you need.
Enjoy

**Comment by tvararu** [comment]
Yep. I'll open issues/pull requests as soon as I get a free moment and start working.
